-- --------------------------------------------------------
-- 主機:                           127.0.0.1
-- 伺服器版本:                        10.3.16-MariaDB - mariadb.org binary distribution
-- 伺服器作業系統:                      Win64
-- HeidiSQL 版本:                  11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- 傾印 randomsentences 的資料庫結構
CREATE DATABASE IF NOT EXISTS `randomsentences` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `randomsentences`;

-- 傾印  資料表 randomsentences.quotations 結構
CREATE TABLE IF NOT EXISTS `quotations` (
  `sum` int(11) NOT NULL AUTO_INCREMENT,
  `text` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `url` mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`sum`)
) ENGINE=InnoDB AUTO_INCREMENT=313 DEFAULT CHARSET=latin1;

-- 正在傾印表格  randomsentences.quotations 的資料：~4 rows (近似值)
/*!40000 ALTER TABLE `quotations` DISABLE KEYS */;
INSERT INTO `quotations` (`sum`, `text`, `url`) VALUES
	(1, '我作為一隻索拉卡，AD死了就是我的問題', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(2, '不要刷帥了，剛剛很糗', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(3, '啊啊啊我想按閃現按不出來', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(4, '會開歌回嗎？欸，額額額額額，會', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(5, '直接上我，你憑什麼，欸嘿嘿嘿嘿嘿，你憑什麼', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(6, '不要聽聊天室那些人亂講，Shiro是清楚的', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(7, '來我們去幹他們，欸，牙敗', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(8, '耳膜還好嗎，我最關注你們的健康了', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(9, '這隻可愛的牛要滾雪球了', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(10, '喔，他那個造型，好大，誒嘿嘿嘿嘿ㄟ', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(11, '對面的人乖乖站好給我撞喔', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(12, '玩打野就不會被吸奶了欸，欸嘿嘿嘿', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(13, '我來了，給你一個抱抱喔，我來找你了，欸嘿嘿嘿嘿', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(14, '皓翔，啊啊啊啊，皓翔，啊啊啊啊，皓翔冷靜，皓翔不要', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(15, '四千訂了，啊，阿烏阿烏阿烏阿', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(16, '你們到十二點就有Muse Dash', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(17, '喔，好長，跟我的差不多長欸', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(18, '啊我是怕你是不是，喔怕，對不起', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(19, '所以白白要安安靜靜的打LOL，打他屁股，沒事沒事', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(20, '我還是很清楚喔，幹他', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(21, '清楚系牛牛', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(22, '索拉卡會拿月亮墮你們喔', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(23, '我是清楚系的@#%!@#$%', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(24, '怕什麼 開戰就贏了', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(25, '先吃呱吉', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(26, '等一下後面 我的屁股', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(27, '晚安 可是沒有吻', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(28, '那魯尬尬', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(29, '速協家 白', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(30, '太帥了吧阿白', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(31, '聊天室有不舉的嗎', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(32, '不要再記名言了，聽我講話', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(33, '吾喔喔喔喔', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(34, '沒有紅綠燈就沒有衝紅燈這回事了', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(35, '哦這裡有眼，哪個渾蛋?', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(36, '(觀眾：步履)...那是念步ㄌㄟˇ嗎', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(37, '放心啦shiro沒事，只會你們有事', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(38, '我很清楚QAQ', 'https://www.youtube.com/watch?v=43pS1xX6pUY'),
	(39, '今天是白淵民', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(40, '我麥快神童欸', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(41, '初見安安，喔，梓凜，喔喔喔喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(42, '我們去揍羊羊', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(43, '先把這隻羊幹掉 欸嘿嘿嘿欸嘿嘿嘿嘿', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(44, '有洞欸 那邊有洞 很大 欸嘿嘿嘿', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(45, 'ㄇㄟㄟㄟㄟㄟ', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(46, '今天是清除的玩麥快喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(47, '巖藝', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(48, '我好了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(49, '哈哈是我啦', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(50, '更上一層樓 一層樓是誰 是你們哦哈哈哈哈', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(51, '我要跟牛牛一起玩 欸嘿嘿', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(52, '你很會扭', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(53, '不喜歡他了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(54, 'pekopekopeko', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(55, '你的全部我都要了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(56, '你要花花嗎?還是你要shiro', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(57, '金搞能挖金嗎', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(58, '你們的家我也要了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(59, 'A', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(60, '這裡怎麼沒門 欸我拆掉了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(61, '讓我睡覺', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(62, '雖然你們裡面的都是爛東西', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(63, '出來玩啊', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(64, '我們今天不會殺任何一隻生物', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(65, '我全部都想要欸', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(66, '牙敗~~', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(67, '我們在玩最和平 A', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(68, '我們是清 清 清除系喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(69, '滾開 滾開 滾開', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(70, '我要這個 滾開 我要噹噹', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(71, '我幹不過他', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(72, '我就想住別人家 不行喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(73, '我也會後空翻', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(74, '他在吹 他在叫', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(75, '麥塊好恐怖', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(76, '不給我我把你變禿頭喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(77, '那是意外', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(78, '麥塊好恐怖', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(79, '等一下殺掉你喔 嘿嘿嘿', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(80, '我有很多草喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(81, '你騙我我討厭你', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(82, '那來看shiro slow run', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(83, '習流又是沙小', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(84, '咩~', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(85, '有豬欸 齁', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(86, '廢物', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(87, '過來嘛(揮劍', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(88, '喂~! 過來 ! 喂 !(吼', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(89, '只有墨囊? 廢物', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(90, '你想死是不是', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(91, '帽子 鼻要', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(92, '講話啊', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(93, '我們今天不會殺任何生物', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(94, '我們只是為了殺牛找一個理由', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(95, 'shiro也是可以吃的', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(96, '等shiro玩完就可以吃了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(97, '我才不會殘殺生物呢', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(98, '(觀眾講紫色蠟燭)「紫色蠟觸」', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(99, '不要吠我', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(100, '我要去養仙人掌', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(101, '住在沙漠好像還可以', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(102, '我是自由的', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(103, '我是技術台', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(104, '我爽就關啊', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(105, '不殺牛的喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(106, '給我東西吃啊草民', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(107, '不殺牛喔，shiro不殺牛喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(108, '有了 我有了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(109, '你是想被我睡嗎', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(110, 'shiro太有文學修養了', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(111, '理化老師你好胖喔', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(112, 'shiro喜歡吃樂事', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(113, '安啦安啦安啦', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(114, '我喜歡木棍', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(115, '我連自己都咬', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(116, '你們要記聚白淵明講的每一句名言', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(117, 'shiro不會做菜 shiro只會吃', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(118, 'MUA', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(119, '好多好快 你們好快 你們好快', 'https://www.youtube.com/watch?v=3A_-5HQqcdw'),
	(120, '把shiro偷偷塞被子裡', 'Discord聊天室'),
	(121, '沒有你們真的會傷心哦QAQ', 'Discord聊天室'),
	(122, '副社當球w', 'Discord聊天室'),
	(123, '太屌了阿白', 'Discord聊天室'),
	(124, '你們.....好色哦QAQ', 'Discord聊天室'),
	(125, '我要進來了哦~', 'Discord聊天室'),
	(126, '永遠都是那個清楚的牧野白呢~', 'Discord聊天室'),
	(127, '你要體驗一下被爆頭的感覺嘛XD', 'Discord聊天室'),
	(128, '哪邊的頭想被爆都可以', 'Discord聊天室'),
	(129, '巨乳蘿莉都是邪教', 'Twitter'),
	(130, '晚安!收隊!睡覺', 'Discord聊天室'),
	(131, '閉嘴閉嘴閉嘴QAQQQQQQQQ', 'Discord聊天室'),
	(132, '我玩minecraft這麼屌', 'Discord聊天室'),
	(133, '我玩RPG都在偷看內褲)Q', 'Discord聊天室'),
	(134, '我的意思是QAQ    不能熬夜QAQ', 'Discord聊天室'),
	(135, '跟泰迪熊幹什麼欸嘿嘿嘿', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(136, '我的泰迪熊沒有洞', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(137, '你給我滾喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(138, 'bango', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(139, '你要吃他哪裡', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(140, '滾開三明治', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(141, '如果泰迪熊是女生 你就不用給他穿衣服了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(142, '怎麼檢查他是不是女生呢 看他有沒有洞', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(143, '泰迪熊不會生氣喔，生氣的話剁掉就好了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(144, '你可以把泰迪熊塞到嘴巴裡哦', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(145, '要是泰迪熊不可愛的話可以把它剁掉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(146, '如果泰迪熊不肯的話 你可以把它剁掉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(147, '要是泰迪熊抓到你的話，你可以把他塞進嘴巴裡', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(148, '那shiro明天不開台了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(149, '你可以永遠、永遠、永遠、永遠離開這裡喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(150, '你們不舉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(151, '早餐是粉喔 粉喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(152, '我要吃粉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(153, '我不知道什麼粉但是黑黑的', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(154, '嗯姆姆姆姆嗯姆姆姆', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(155, '我會殺泰迪熊，不會裝可愛', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(156, '(觀眾問：要怎麼看男女)「你要看它有幾個洞」', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(157, '什麼太長 shiro也覺得我太長', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(158, '我有兩顆洞 卍', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(159, '泰迪熊叫什麼名字 他叫 卍我有兩顆洞卍', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(160, '我有兩個洞', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(161, '白白有在讀書？白白沒有', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(162, '被老爸淦 趕出家門', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(163, '被老爸幹...出家門', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(164, '被老爸趕出家門~趕啦！趕啦', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(165, '大家都邊緣啦', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(166, 'shiro不會丟下你們喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(167, '正常那邊會希望我不戴', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(168, '放在這裡比較舒服', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(169, '初見安安？你最好是初見啦！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(170, '一萬就卍解啦！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(171, '給我再去死一次', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(172, '青蛙你給我再去死一次！舉手不是舉很爽？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(173, '我怕生', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(174, '社長我怕', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(175, 'shiro 在吃什麼 粉喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(176, 'shiro會很多髒話喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(177, '來單挑啦', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(178, '哞~(比較香)', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(179, 'shiro會哞嗎 哞~~~', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(180, '可以踩我嗎「 不行」', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(181, '「啾」 ', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(182, 'shiro可以去學各個國家的髒話 然後罵給你聽', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(183, '去跟別的國家的v連動 一去就跟他講 FAQ', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(184, '白白有一段時間是失身了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(185, 'Ahoy!Ahoy!', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(186, '我是小朋友逆', 'https://www.youtube.com/watch?v=41-Hl_TZzZs'),
	(187, 'ロリ', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(188, '蘿莉蘿莉蘿莉蘿莉蘿莉蘿莉蘿莉蘿莉蘿莉蘿莉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(189, 'boingboing不是邪教 但是boingboing蘿莉是邪教', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(190, 'shiro wa kyomokawaii', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(191, '白は〜今日もかわいい', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(192, '聽說訂閱要點兩下？聽說你的頭要敲兩下哦', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(193, 'SOHAI', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(194, '基本上我看的都是H漫喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(195, '白白有推薦的車碼嗎？我會放在dc的nsfw裡', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(196, '你們要畫面白白的本子嗎？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(197, '平的就好', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(198, '你們不是要畫H本嗎？我要看欸', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(199, 'H本頻道？沒關係啊！shiro覺得YT不知道就好了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(200, 'shiro會把你們割掉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(201, 'shiro覺得你們是女的你們就會是女的哦！我會把你割掉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(202, '你繼續去D阿！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(203, '白白你自己還沒有18歲？啊哈！啊哈！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(204, '玩喔 很多喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(205, '社長打球囉！社長當球', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(206, '你說的是18禁遊戲還是正常遊戲', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(207, '沙耶之歌棒', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(208, '社長男生還是女生？他是一隻nya', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(209, '你們可以去檢查一下社長？看他有幾個洞', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(210, '白白的飲食很均衡', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(211, '哪個都很痛苦,不要比', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(212, '對 很不正常喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(213, '我那個還沒有玩過欸', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(214, '阿白好屌喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(215, '你搶走我男朋友 我要跟你單挑', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(216, '草民編號是指被吃掉的順序嗎', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(217, 'shiro的18公分不是長在下面是長在上面好嗎', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(218, '那是誰的奶？那是誰的？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(219, 'shiro不是乳牛 不是乳牛', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(220, '白白今天要幾點睡覺？不知道', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(221, '他還滿的！他還滿的！我不想吃了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(222, '白沒有奶所以不是乳牛？你在供三小！？？？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(223, '你們在供殺小', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(224, '渾沌好吃', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(225, '什麼？什麼混沌？渾沌好吃？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(226, '吃我拜託', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(227, '是餛飩！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(228, '我是餛飩系', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(229, '白覺得庫拉皮卡會下船嗎?總有一天會的...吧?', '不明'),
	(230, '社長!員工餐啦!社長', '不明'),
	(231, 'shiro想怎樣就怎樣啦', '不明'),
	(232, '我是餛飩系！', '不明'),
	(233, '他都是毛！', '不明'),
	(234, '我可以吃社長', '不明'),
	(235, '他吃過的我不要', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(236, '我不是喝水 你們也可以刷喝口水', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(237, '不要再刷喝口水', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(238, '先喝口（水）綠茶', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(239, '我是餛飩系', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(240, '他吃過的我不要', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(241, '我可以吃社長', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(242, '八方雲集我真的沒吃過欸', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(243, '你要吃nya嗎', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(244, '你們這群混蛋！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(245, '來啊 來啊 你們這群渾蛋', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(246, '20分鐘那位', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(247, '欸17分了 欸我們聊到30分好了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(248, '你們現在才知道啊！shiro才是規則', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(249, '我們聊到明天吧', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(250, 'shiro才是規則', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(251, '給我記住 shiro才是規則', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(252, '輕鬆 治癒的 蘿莉', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(253, '白白都用耙子做什麼事？殺人哦~', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(254, '你們能來我就能die', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(255, '警察表示殺小？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(256, '不是免費仔你們也都是我的草民喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(257, '誰不喜歡？站出來！我們來單挑', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(258, '誰不喜歡牛牛', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(259, '我喝口（水）東西', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(260, '不倒讚的是我喜歡的人', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(261, '斬草囉~~', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(262, '不會倒讚只會退訂閱. 蛤！？(╯°□°）╯', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(263, '你是不是要被敲！？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(264, '白白沒有球. 蛤！？蛤！？蛤！？蛤！？什麼？什麼？什麼？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(265, '倒讚就倒阿', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(266, '我不喜歡做運動', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(267, '沒有讓你們喜歡是我的問題,對！不！起！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(268, '按讚的人比倒讚的人多就好多就好', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(269, '養我', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(270, '不要,我要草民養我.草民,養我', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(271, '情緒台要關掉了啦', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(272, '不是情趣台啦 ！情緒台', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(273, '45分最後囉!!', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(274, '(觀眾：白白聽話讓我看看)「你要看哪裡？*4」', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(275, '(觀眾：白白你長的好看嗎)「你們覺得呢？（威壓）」', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(276, '「要看經費阿 社長沒錢啊 瑞塔沒錢啊」', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(277, '白白除了胸部都超棒.你在講什麼？？！！！！？？？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(278, '瑞塔超爽喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(279, '我基本上連早餐都不吃哦！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(280, '滾開泰迪熊！把你衣服脫掉！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(281, '看著我', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(282, '我最喜歡你了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(283, '我接受boi了', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(284, 'shiro硬硬的', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(285, '白白硬硬的 shiro硬硬的', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(286, '哪裡硬硬的？是歐派？骨頭啦！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(287, 'Shiro下面什麼都沒有喔~ 沒有一大包啦!!', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(288, '(觀眾：白白你往下看看得到腳趾對吧)「看不到哦！(^^)」', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(289, '你們是看罩杯決定人的性別的嗎？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(290, '不是我的一大包', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(291, '我是女的！沒有那根棒', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(292, '沒有A- 窩不知道', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(293, '5ma是什麼？', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(294, '你們好耶什麼', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(295, '我喜歡你也可以有人與獸的交流啊！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(296, '是灰色的啦！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(297, '社長沒錢哪！', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(298, '下面什麼也沒有，shiro沒有一大包喔', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(299, '你在講什麼阿*2', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(300, '雅敗，好了關台了再見', 'https://www.youtube.com/watch?v=41-Hl_TZzZs '),
	(301, 'Koumi你是在自肥嗎？', '不明'),
	(302, '那植物人算植物還是人', 'Discord聊天室'),
	(303, '诶嘿嘿~shiro最喜歡打架了哦', 'Discord聊天室'),
	(304, '有問題沒關係 解決有問題的人就好', 'Discord聊天室'),
	(305, 'shiro最會開車惹ww诶嘿嘿', 'Discord聊天室'),
	(306, '社長想被剁掉嗎', 'Discord聊天室'),
	(307, '出征討伐', 'Discord聊天室'),
	(308, '我來帶你回家了xD', 'Discord聊天室'),
	(309, '草民全部帶回家啦www', 'Discord聊天室'),
	(310, 'shiro可以一天多個', 'Discord聊天室'),
	(311, '我想聽你骨頭掉下來的聲音', 'Discord聊天室'),
	(312, '真的可以跟草民一起睡了w', 'Discord聊天室');
/*!40000 ALTER TABLE `quotations` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
